config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/fair-software/howfairis:
      branch: main
      repo: https://github.com/fair-software/howfairis
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/fair-software/howfairis git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-russet-ray.sh
        container: qc.acc_cloudy-cinnabar-lynx
  QC.Doc:
    repos:
      github.com/fair-software/howfairis find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-amber-urchin.sh
        container: qc.doc_chummy-persimmon-raccoon
      github.com/fair-software/howfairis git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-lavender-mongrel.sh
        container: qc.doc_wheezy-champagne-frigatebird
      github.com/fair-software/howfairis markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-razzmatazz-hippopotamus.sh
        container: qc.doc_zippy-orange-zonkey
      github.com/fair-software/howfairis restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-tangerine-eleuth.sh
        container: qc.doc_thirsty-corn-dunker
  QC.Lic:
    repos:
      github.com/fair-software/howfairis licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-burgundy-tarantula.sh
        container: qc.lic_hasty-amber-bee
  QC.Met:
    repos:
      github.com/fair-software/howfairis cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.randy-emerald-crocodile.sh
        container: qc.met_cheeky-jade-woodpecker
      github.com/fair-software/howfairis validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-coral-giraffe.sh
        container: qc.met_nerdy-plum-stingray
  QC.Sec:
    repos:
      github.com/fair-software/howfairis bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-mauve-jaguar.sh
        container: qc.sec_muzzy-orchid-impala
  QC.Sty:
    repos:
      github.com/fair-software/howfairis flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-pink-wolverine.sh
        container: qc.sty_sleepy-beige-crane
      github.com/fair-software/howfairis hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-orange-buzzard.sh
        container: qc.sty_sickly-scarlet-caiman
      github.com/fair-software/howfairis jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-orchid-panda.sh
        container: qc.sty_breezy-sapphire-insect
  QC.Ver:
    repos:
      github.com/fair-software/howfairis get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-ruby-horse.sh
        container: qc.ver_snazzy-tan-russel
timeout: 5400
