config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/fair-software/howfairis:
      branch: main
      repo: https://github.com/fair-software/howfairis
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/fair-software/howfairis git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-purple-wolverine.sh
        container: qc.acc_slimy-malachite-bison
  QC.Doc:
    repos:
      github.com/fair-software/howfairis find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-pink-magpie.sh
        container: qc.doc_sleepy-flax-akita
      github.com/fair-software/howfairis git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-peach-maltese.sh
        container: qc.doc_slimy-charcoal-kakapo
      github.com/fair-software/howfairis markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-wheat-barb.sh
        container: qc.doc_lovely-chestnut-raccoon
      github.com/fair-software/howfairis restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-gold-ostrich.sh
        container: qc.doc_freaky-magenta-spitz
  QC.Lic:
    repos:
      github.com/fair-software/howfairis licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-coral-dodo.sh
        container: qc.lic_flaky-mauve-tarantula
  QC.Met:
    repos:
      github.com/fair-software/howfairis cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-mauve-angelfish.sh
        container: qc.met_wimpy-plum-setter
      github.com/fair-software/howfairis validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-khaki-paradise.sh
        container: qc.met_shaky-cardinal-cheetah
  QC.Sec:
    repos:
      github.com/fair-software/howfairis bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-mauve-uguisu.sh
        container: qc.sec_skanky-tangerine-cow
  QC.Sty:
    repos:
      github.com/fair-software/howfairis flake8:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-turquoise-bee.sh
        container: qc.sty_cloudy-heliotrope-hummingbird
      github.com/fair-software/howfairis hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-ultramarine-woodpecker.sh
        container: qc.sty_paltry-cream-heron
      github.com/fair-software/howfairis jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-ecru-dragon.sh
        container: qc.sty_cloudy-beige-kakapo
  QC.Ver:
    repos:
      github.com/fair-software/howfairis get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-tomato-baboon.sh
        container: qc.ver_smelly-fuchsia-zonkey
timeout: 5400
